export default {
    placeholder: {
        name: 'Фамилия',
        surname: 'Имя',
        driverSerialNumber: 'Серия и номер прав',
        driverCountry: 'Страна прав',
        category: 'Категория',
        carNum: 'Номер автомобиля',
        mark: 'Марка',
        model: 'Модель',
        color: 'Цвет',
        year: 'Год',
        workPhoneNumber: 'Раб. телефон',
        phoneNumber: 'Телефон',
        email: 'Почта',
        comment: 'Коментарии',
        registerDate: 'Дата рег.',
        countryByPhone: 'Страна (По коду телефона)',
        driverRegisterDate: 'Стал водителем',
        dateOfIssueLicense: 'Дата выдачи',
        validUntil: 'Действует до',
        dateVerification: 'Дата верификация',
        dateOfBirth: 'Дата рождения',
        codeInn: 'Код ИНН',
        country: 'Страна',
        region:'Регион',
        city: 'Город',
        index: 'Индекс',
        address: 'Адрес',
        gender: 'Пол',
        passportOrId: 'Паспортные данные или ID',
        clientLastLogin: 'Kлиент',
        driverLastLogin: 'Водитель',
        clientLastOrderDate: 'Kлиент',
        driverLastOrderDate: 'Водитель',
        idGuest: 'Id пригласителя:',
        operationSystem: 'ОС',
        carMark: 'Маркa машин',
        cordinate: 'Координаты',
        appVersion: 'Версии приложений',
        language: 'Язык',
        day: 'День',
        months: 'Месяц',
        
    },
    photoControlHeaderText: 'Фотоконтроль водителя',
    personalDataText: 'Личные данные',
    car: 'Автомобиль',
    driverLicense: 'Водительское удостоверение',
    verification: 'Верификация',
    lastLoginDate: 'Дата последнего входа',
    lastOrderDate: 'Дата последнего заказа',
    tarrifText: 'Тариф'
}